spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yourlhub # FIXME 環境変数で制御する
    username: yourlhub # FIXME 環境変数で制御する
    password: yourlhub # FIXME 環境変数で制御する
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 50
      idle-timeout: 60000
      maxLifetime: 580000
      connection-test-query: SELECT 1
  graphql:
    graphiql:
      enabled: true # FIXME 環境変数で制御する
  jackson:
    time-zone: Asia/Tokyo
    serialization:
      indent-output: true
server:
  port: 8080
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: access_log
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
logging:
  level:
    root: info
    com:
      yourlhub:
        interfaces:
          database: DEBUG
  file:
    name: spring.log
mybatis:
  configuration:
    map-underscore-to-camel-case: true
app:
  jwt:
    secret: yourlHubjwt1998samplejwtsecretthisisapenyyyyy # FIXME 環境変数で制御する
    issuer: yourlHub # FIXME 環境変数で制御する